version: '3.8'
services:
  intake:
    build:
      context: .
      dockerfile: intake/Dockerfile
    restart: always
    ports:
      - '8080:8080'
    environment:
      - HTTP_DEBUG=true
      - HTTP_PORT=80
      - S3_BUCKET=lurien-data