version: '3.8'

services:
  intake:
    build:
      context: .
      dockerfile: intake/Dockerfile
    restart: always
    ports:
      - '8080:80'
    environment:
      - HTTP_DEBUG=true
      - HTTP_PORT=80
      - S3_BUCKET=lurien-data
      - S3_ENDPOINT=http://minio:9000
      - S3_KEY=dummyminiouser
      - S3_SECRET=dummyminiopassword
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio:/data
    environment:
      MINIO_ROOT_USER: dummyminiouser
      MINIO_ROOT_PASSWORD: dummyminiopassword
    command: server --address 0.0.0.0:9000 --console-address 0.0.0.0:9001 /data
  
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 dummyminiouser dummyminiopassword;
      /usr/bin/mc mb myminio/lurien-data;
      /usr/bin/mc policy set public myminio/lurien-data;
      exit 0;
      "

volumes:
  minio: